import React from "react";
import imgex from "../assets/FotoOfficerIEEE.png";


const users = [
  {
    id: 1,
    title: "Tony Reichert",
    desc: "Management",
    category: "news",
    avatar: imgex,
    date: "tony.reichert@example.com",
  },
  {
    id: 2,
    title: "Zoey Lang",
    desc: "Development",
    category: "event",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    date: "zoey.lang@example.com",
  },
  {
    id: 3,
    title: "Jane Fisher",
    desc: "Development",
    category: "news",
    avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
    date: "jane.fisher@example.com",
  },
  {
    id: 4,
    title: "William Howard",
    desc: "Marketing",
    category: "event",
    avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
    date: "william.howard@example.com",
  },
  {
    id: 5,
    title: "Kristen Copper",
    desc: "Sales",
    category: "news",
    avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    date: "kristen.cooper@example.com",
  },
  {
    id: 6,
    title: "Brian Kim",
    desc: "Management",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    date: "brian.kim@example.com",
    category: "news",
  },
  {
    id: 7,
    title: "Michael Hunt",
    desc: "Design",
    category: "event",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29027007d",
    date: "michael.hunt@example.com",
  },
  {
    id: 8,
    title: "Samantha Brooks",
    desc: "HR",
    category: "news",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e27027008d",
    date: "samantha.brooks@example.com",
  },
  {
    id: 9,
    title: "Frank Harrison",
    desc: "Finance",
    category: "event",
    avatar: "https://i.pravatar.cc/150?img=4",
    date: "frank.harrison@example.com",
  },
  {
    id: 10,
    title: "Emma Adams",
    desc: "Operations",
    category: "news",
    avatar: "https://i.pravatar.cc/150?img=5",
    date: "emma.adams@example.com",
  },
  {
    id: 11,
    title: "Brandon Stevens",
    desc: "Development",
    category: "news",
    avatar: "https://i.pravatar.cc/150?img=8",
    date: "brandon.stevens@example.com",
  },
  {
    id: 12,
    title: "Megan Richards",
    desc: "Product",
    category: "event",
    avatar: "https://i.pravatar.cc/150?img=10",
    date: "megan.richards@example.com",
  },
  {
    id: 13,
    title: "Oliver Scott",
    desc: "Security",
    category: "news",
    avatar: "https://i.pravatar.cc/150?img=12",
    date: "oliver.scott@example.com",
  },
  {
    id: 14,
    title: "Grace Allen",
    desc: "Marketing",
    category: "news",
    avatar: "https://i.pravatar.cc/150?img=16",
    date: "grace.allen@example.com",
  },
  {
    id: 15,
    title: "Noah Carter",
    desc: "I. Technology",
    category: "event",
    avatar: "https://i.pravatar.cc/150?img=15",
    date: "noah.carter@example.com",
  },
  {
    id: 16,
    title: "Ava Perez",
    desc: "Sales",
    category: "news",
    avatar: "https://i.pravatar.cc/150?img=20",
    date: "ava.perez@example.com",
  },
  {
    id: 17,
    title: "Liam Johnson",
    desc: "Analysis",
    category: "news",
    avatar: "https://i.pravatar.cc/150?img=33",
    date: "liam.johnson@example.com",
  },
  {
    id: 18,
    title: "Sophia Taylor",
    desc: "Testing",
    category: "news",
    avatar: "https://i.pravatar.cc/150?img=29",
    date: "sophia.taylor@example.com",
  },
  {
    id: 19,
    title: "Lucas Harris",
    desc: "Information Technology",
    category: "event",
    avatar: "https://i.pravatar.cc/150?img=50",
    date: "lucas.harris@example.com",
  },
  {
    id: 20,
    title: "Mia Robinson",
    desc: "Operations",
    category: "news",
    avatar: "https://i.pravatar.cc/150?img=45",
    date: "mia.robinson@example.com",
  },
];

export {users};
